### ISSUE TITLE
Refresh Token Invalidating the current session

### ISSUE THREAD

**Issue by abinashdatta** [auth0/express-openid-connect#279] opened 2021-09-13 16:14 UTC
The `refresh token function` under` req.oidc.accessToken` invalidating the current session and enforcing `auth_code flow` again post refresh. I want an option to use refresh token flow to create a new access token without invalidating current session and keeping `user` and` id token `info intact in `req.oidc` object. 

Please note `req.oidc.user and req.oidc.idToken `are coming as undefined after refresh() call.

**Comment by adamjmcgrath** [comment] 2021-09-14 10:58
Hi @abinashdatta - I can't reproduce your issue using the following steps

- Run the example app (​https://github.com/auth0/express-openid-connect/blob/master/examples/access-an-api.js) `npm run start:example -- access-an-api`
- Wait for the AT to expire
- Refresh the page
- AT is refreshed and user remains logged in 

Can you share some example code that demonstrates the issue?

**Comment by adamjmcgrath** [comment] 2021-10-11 10:03
Closing due to innactivity, feel free to ping me if you'd like to reopen

**Closed by adamjmcgrath** 2021-10-11 10:03 UTC
Labels: more info needed
