### ISSUE TITLE
BadRequestError: checks.state argument is missing only on chrome

### ISSUE THREAD

**Issue by tigus** [auth0/express-openid-connect#267] opened 2021-07-30 12:02 UTC
Hello,

I get trouble on callback route in localhost (in https via caddy) and in production but only in chrome
I got a infinite look who finished by this error: BadRequestError: checks.state argument is missing but it happens only on chrome

I read that many people got trouble in localhost but for my case it's in production too... but on firefox or safari, it works...
My production website is on https too.
I test on a mac and a windows computer same result. my chrome setup accepts all kind of cookie ! 

I don't find the solution...
If someone can help me

i use express-openid-connect 2.5.0

you can see here my config
```js
app.use(auth({
  authorizationParams: {
    response_type: 'code'
  },
  clientSecret: process.env.secret,
  authRequired: false,
  auth0Logout: true,
  baseURL: process.env.BASE_URL,
  clientID: process.env.CLIENT_ID,
  issuerBaseURL: process.env.ISSUER_BASE_URL,
}))
```

**Comment by adamjmcgrath** [comment] 2021-08-20 14:03
Hi @tigus - thanks for raising this

I can't see anything wrong with your config and I can't reproduce your issue on `https://localhost` running behind caddy.

`checks.state argument is missing` is suggesting that the cookies you dropped on your login page aren't being picked up on your callback page.

If you inspect the `Cookies` tab of your callback request handler in the Network tab you should see the `auth_verification` cookie, that has the `checks.state` argument in it, eg

![image](https://user-images.githubusercontent.com/1299658/130245350-964d21e8-0ae9-4547-aa59-7435f73b8252.png)

**Comment by adamjmcgrath** [comment] 2021-09-14 11:01
Closing due to innactivity

**Closed by adamjmcgrath** 2021-09-14 11:01 UTC
Labels: more info needed
