### ISSUE TITLE
Typescript: Type incompatibility with connect-redis

### ISSUE THREAD

**Issue by ramraphael** [auth0/express-openid-connect#270] opened 2021-08-06 19:22 UTC
### Describe the problem

Hey team! I'm following [this example](https://github.com/auth0/express-openid-connect/blob/d529ea0d22f09af41d303e0141d562749cba448a/EXAMPLES.md#9-use-a-custom-session-store) to implement `connect-redis` for shared session storage, but it's leading to a type error.

For further context, I am using DefinitelyTyped's type definitions for `connect-redis`, `@types/connect-redis` (the latest, v0.0.17).

The block of code that leads to the type error:
```ts
  import { auth } from "express-openid-connect";
  import connectRedis from "connect-redis";
  import redis from "redis";

  const RedisStore = connectRedis(auth);
  const redisClient = redis.createClient(configSettings.redisUrl);

  app.use(
    auth({
      ...settings.auth0Config,
      session: {
        // Type incompatibility with store
        // changing this to store: new RedisStore({ client: redisClient }) as any leads to this working as expected
        store: new RedisStore({ client: redisClient })
      }
    })
  );
```

The type error being thrown:
```ts
Type 'RedisStore' is not assignable to type 'SessionStore'.
  Types of property 'get' are incompatible.
    Type '(sid: string, callback: (err: any, session?: SessionData) => void) => void' is not assignable to type '(sid: string, callback: (err: any, session?: SessionStorePayload) => void) => void'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'session' and 'session' are incompatible.
          Type 'SessionData' is missing the following properties from type 'SessionStorePayload': header, datats(2322)
index.d.ts(537, 3): The expected type comes from property 'store' which is declared here on type 'SessionConfigParams'
```

### What was the expected behavior?

As stated in the docs, express-session compatible stores (like connect-redis) should be type-compatible with `express-openid-connect`. Unfortunately, there seems to be a type mismatch.

### Reproduction

- Set up `express-openid-connect` in a Node/Express/Typescript app
- Set up `connect-redis` to use redis for session storage, following [this example](https://github.com/auth0/express-openid-connect/blob/d529ea0d22f09af41d303e0141d562749cba448a/EXAMPLES.md#9-use-a-custom-session-store)
- See error statement above

### Environment
- "express": "^4.17.1",
- "express-openid-connect": "^2.5.0",
- "connect-redis": "^6.0.0",
- "redis": "^3.1.2"
- "@types/connect-redis": "^0.0.17",
- "typescript": "^4.2.3"

I'm unable to provide a minimum example app at the moment (this error was encountered while developing a private project), but I'm more than happy create one if needed.

Thank you all for making this lib. It's made it incredibly easy to implement Auth0 authorization.

**Comment by adamjmcgrath** [comment] 2021-08-17 16:07
Hi @ramraphael - thanks for raising this

This is a duplicate of #234 - so will close this in favor of that. Please continue to use your workaround for now

**Closed by adamjmcgrath** 2021-08-17 16:07 UTC
