### ISSUE TITLE
Every actions in Express will trigger redis set action and get action automatically

### ISSUE THREAD

**Issue by q897586834** [auth0/express-openid-connect#407] opened 2022-10-28 09:39 UTC
### Describe the problem

when I use auth() as middleware and config a custom store in Express , there is a logic in appSession.js line 349 said it will do set action automatically without any condition. So when there is any action in Express these redis actions will be executed automatically but it can't be controled

### What was the expected behavior?

add a addition flag to control 

### Reproduction

1.use auth(config) as middleware in Express with a custom store
2.call api in Express
3.see redis log there are many times get and set actions

### Environment

    "connect-redis": "^6.1.1",
    "express": "^4.17.3",
    "express-openid-connect": "^2.7.1",

**Comment by adamjmcgrath** [comment] 2022-10-28 10:24
Hi @q897586834 - thanks for raising this

This is expected behaviour - the session by default is a rolling session (24hrs by default), so a new expiry must be written to the session on every request

Closing this as it's working as intended

**Closed by adamjmcgrath** 2022-10-28 10:24 UTC
