### ISSUE TITLE
issuer form response_mode: 'form_post'

### ISSUE THREAD

**Issue by BredSt** [auth0/express-openid-connect#122] opened 2020-08-09 15:01 UTC
Hello,

we use the auth config which works with other library 

```
app.use(
    auth({
     issuerBaseURL: `${URL}/.well-known/openid-configuration`,
     authorizationParams: {
    ...
     response_mode: 'form_post',
    }

```

while running it we got an error, that the issuer supporting only `query` of `fragment` 
but not, we have old applications which works with the **exact same issuer**  and we configure the `issueBaseURL ` exactly the same and the `response_mode` is
 **form_post**, why we are getting this error,is it known issue ?  please explain how to proceed.

**Comment by BredSt** [comment] 2020-08-10 15:36
it will be great if someone can assist, or explain why we have this difference, as my team is currently stuck and cannot proceed.

**Comment by BredSt** [comment] 2020-08-14 16:21
To make it more clear, I use golang and print the URL server output 

![image](https://user-images.githubusercontent.com/69369419/90270732-5789d200-de63-11ea-98ba-3c30bf7a2097.png)

**Comment by BredSt** [comment] 2020-08-14 16:23
if this lib not maintained anymore please let me know,

**Comment by stevehobbsdev** [comment] 2020-08-14 20:59
Hi @BredSt, sorry this wasn't picked up sooner. It wasn't clear to me what error you are receiving from your initial report - could you share the exact error message you're getting?

Thanks

**Comment by BredSt** [comment] 2020-08-15 10:26
HI @stevehobbsdev  , 
One things that I dont understand we use before the 
https://github.com/panva/node-openid-client 
and put in the  `response_mode: 'form_post',`  **for the exact same issuer**
and when using the express-openid repo we got error : , **that the issuer supporting only query of fragment**,
we are 3 people which work on it and we dont understand why we got this erorr,
I've change it to `query` (not sure) and its working, however
And the below code doesnt works, 
while **debug** the application 
I see that it stops on the `getUser` and not in the `handleCallback` hence I dont get the user identity .
This is the full code, could you please advice ?

```
const { auth, requiresAuth } = require('express-openid-connect');
  const session = require('express-session');
  const bodyParser = require('body-parser');
    
    module.exports = async (app) => {
    
      const ClientId = process.env.CI;
      const ClientSecret = process.env.CS;
      const URL = process.env.S_URL;
    
      app.use(session({
         name: 'bat-auth',
         secret: 'cookie-secret',
      }));

      app.use(bodyParser.json());
      app.use(bodyParser.urlencoded({ extended: true }));
    
      app.use(auth({
          clientSecret: ClientSecret,
          issuerBaseURL: `${URL}`,
          clientID: ClientId,
          baseURL: process.env.REDT_URL,
          redirectUriPath: '/redirect',  //my app redirect route
          authorizationParams: {
           response_type: 'code',
           response_mode: 'form_post',
           scope: 'openid',
          },
        async handleCallback(req, res, next) {
           req.session.openidTokens = req.openidTokens;
           console.log('---req.openidTokens', req.openidTokens);
           req.session.userIdentity = req.openidTokens.claims();
          next();
        },
        async getUser(req) {
           return req.session.userIdentity;
        },
      }));

  app.get('/', (req, res) => {
    const tokenSet = req.openid.makeTokenSet(req.session.openidTokens);
    console.log(`tokenset root: ${tokenSet}`);

    res.send(req.isAuthenticated() ? 'Logged in' : 'Logged out');
  });
  app.get('/redirect', async (req, res) => {
    const tokenSet = req.openid.makeTokenSet(req.session.openidTokens);
    console.log(`tokenset: ${tokenSet}`);
    console.log('redirect called');
    res.send('redirect called');
  });
```

**Comment by adamjmcgrath** [comment] 2020-08-15 11:19
Hi @BredSt 

> and put in the response_mode: 'form_post', for the exact same issuer
> and when using the express-openid repo we got error : , that the issuer supporting only query of fragment,

The default response_type for `node-openid-client` is `code` (https://github.com/panva/node-openid-client/blob/master/docs/README.md#new-clientmetadata-jwks-options), the default for this sdk is `id_token` (https://github.com/auth0/express-openid-connect/blob/master/API.md#authorization-params-key) - we chose `id_token` because this library is primarily for login, it's an "Express JS middleware implementing _sign on_ for Express web apps using OpenID Connect."

If your `response_mode` is `form_post` and your `response_type` was defaulting to `id_token`, then you will be using the "Implicit Grant". If you look at the `grant_types_supported` in your OP (https://github.com/auth0/express-openid-connect/issues/122#issuecomment-674153172) you'll notice that "implicit" is not in that list ,and therefore not supported. This will explain your (slightly opaque) error `the issuer supporting only query of fragment` and also explains why "I've change it to query (not sure) and its working," - when you changed it to `code` - you switched to the `authorization_code` grant, which is supported by your OP.

> And the below code doesnt works,
> while debug the application
> I see that it stops on the getUser and not in the handleCallback hence I dont get the user identity .

I'm not entirely sure what your error is is, but if I look at your code - I see a couple of potential issues:

- you're using custom express-session mw: while this is not a problem per se, you don't need it - the app will create a cookie session which you can access at `req.appSession` (the name can be configures in the `appSession.name` config https://github.com/auth0/express-openid-connect/blob/master/API.md#optional-keys)
- you're overwriting the `redirectUriPath`: the auth middleware will add a handler to `redirectUriPath` to handle the callback from the auth server. This will be a get or post handler depending on whether you're using `form_post` or `query`. Your using form_post, so it will be a post - you're adding a get, so should be fine - but might be a source of confusion

If you can give me more information on the steps to reproduce your error with that code and how you're expecting it to work I might be able to help you debug it.

**Comment by BredSt** [comment] 2020-08-15 13:51
HI @adamjmcgrath  - Thanks for the answer,

1 . Do you want me to change something in the `authorizationParams:` ? , 

as I try also

        authorizationParams: {
            response_type: 'id_token',
            //response_mode: 'query',
            scope: 'openid',
            response_mode: 'form_post',
        }, 

And I still get the same error.

2. In the authorisation server we assigned our application with http://app:host/redirect as after succefull user login the auth server should call to the app "/redirect" path. should I remove the the `getUser` and `handlecallBack` and keep only the `/redirect` route ?

**Comment by BredSt** [comment] 2020-08-15 13:59
HI @adamjmcgrath  

Btw, to make it clearer , this is the working implematation for the **same issuer and client id and client secret**
You can see that we use explicit the `form_data` .
what am I missing here to make it work.?  


```
const { Issuer, Strategy } = require('openid-client');
const cookieParser = require('cookie-parser');
const cookieSession = require('cookie-session');
const bodyParser = require('body-parser');
const passport = require('passport');
const userList = require('./userlist');
module.exports = async (app) => {
    let oSrv;
    const durl = `${process.env.srvurl}/.well-known/openid-configuration`;
    try {
        oSrv = await Issuer.discover(durl);
    } catch (err) {
        console.log('error', err);
        return;
    }

    app.get('/', autUser(), passport.authenticate('oidc'));

    const oSrvCli = new oSrv.Client({
        client_id: process.env.CI,
        client_secret: process.env.CS,
        token_endpoint_auth_method: 'client_secret_basic',
    });

    passport.serializeUser((user, done) => {
        done(null, user);
    });
    passport.deserializeUser((obj, done) => {
        done(null, obj);
    });

    const cfg = {
        scope: 'openid',
        redirect_uri: process.env.RE_URL,
        response_type: 'code',
        response_mode: 'form_post',
    };

    const autUser = () => (req, res, next) => {
        passport.use(
            'oidc',
            new Strategy({ oSrvCli, cfg }, (tokenset, done) => {
                const claims = tokenset.claims();
                const user = {
                    name: claims.name,
                    id: claims.sub,
                    id_token: tokenset.id_token,
                };
                return done(null, user);
            }),
        );
        next();
    };
    app.use(
        bodyParser.urlencoded({
            extended: false,
        }),
    );
    app.use(cookieParser('red-hat'));
    app.use(
        cookieSession({
            name: 'red-hat',
            secret: 'csect',
        }),
    );

    app.use(passport.initialize());
    app.use(passport.session());

    app.get('/redirect', async (req, res, next) => {
        await passport.authenticate('oidc', async (err, user) => {
            if (err) {
                console.log(`Authentication failed: ${err}`);
                return next(err);
            }
            if (!user) {
                return res.send('no identity');
            }
            req.login(user, async (e) => {
                if (e) {
                    console.log('not able to login', e);
                    return next(e);
                }
                try {
                    // At the end we need the user.id_token
                    const url = await userList.GetUsers(user.id_token);
                    // print last log
        
                    return res.redirect(url);
                } catch (er) {
                    res.send(er.message);
                }
            });
        })(req, res, next); 
};

```

**Comment by adamjmcgrath** [comment] 2020-09-02 14:31
Hi @BredSt - apologies for the inactivity

Are you still looking for support with this issue or have you resolved it?

**Comment by adamjmcgrath** [comment] 2020-10-16 10:26
Hi @BredSt - closing for now, feel free to reopen if you have any other questions

**Closed by adamjmcgrath** 2020-10-16 10:26 UTC
