### ISSUE TITLE
After callback, req.oidc.accessToken and req.oidc.user are undefined

### ISSUE THREAD

**Issue by askurat** [auth0/express-openid-connect#235] opened 2021-05-13 17:00 UTC
### Describe the problem

After authentication req.oidc returns undefined for all variables which include: req.oidc.accessToken and req.oidc.user. Upon investigation, I noticed my session always returns an empty object. What would cause it to be empty?

Here is my config:
```
const authRequestHandler = auth({
  issuerBaseURL: process.env.IDENTITY_URL,
  baseURL: process.env.BASE_URL,
  clientID: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
  secret: process.env.COOKIE_SECRET,
  authRequired: false,
  idpLogout: true,
  routes: {
    callback: '/cb',
  },
  authorizationParams: {
    scope: 'openid profile',
    response_type: 'code',
  },
});
```

### What was the expected behavior?

req.oidc.accessToken should have information on callback. appSession shouldn't be blank.

### Environment

- **Version of this library used:** v2.4.0
- **Express Version:** v4.17.1

**Comment by adamjmcgrath** [comment] 2021-05-14 11:16
Hi @askurat - I can't see anything wrong with your config and I don't know what would cause the session to be empty after a successful login.

Are you getting any errors in your logs? If you could create a minimal application that reproduces the issue I could debug it for you.

**Comment by askurat** [comment] 2021-05-14 16:58
@adamjmcgrath Thanks for the quick reply. It is hard to reproduce as this is an enterprise app. I did strip down my app.js file to just the login portion and I still cannot get user info:
```
const express = require('express');
const { auth } = require('express-openid-connect');
console.log('Loaded required packages!');

console.log('Loading configuration file');
// Config
const config = require('./config.js');

console.log('Loaded configuration file!');

const nodeEnv = config.NODE_ENV;
const expressPort = config.PORT;

// Assign http server
const app = express();

app.use(
  auth({
    issuerBaseURL: process.env.IDENTITY_URL,
    baseURL: process.env.BASE_URL,
    clientID: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    secret: process.env.COOKIE_SECRET,
    idpLogout: true,
    authRequired: false,
    authorizationParams: {
      response_type: 'code',
      // response_mode: 'query',
      scope: 'openid profile email',
    },
    routes: {
      callback: '/cb',
    },
  })
);

app.get('/', (req, res) => {
  res.send(`hello ${req.oidc.user.sub}`);
});


app.get('/login/cb', (req, res) => {
  res.send(`hello ${req.oidc.isAuthenticated()}`);
});

console.info('Starting http server');

// Start http server
const server = app.listen(expressPort, function () {
  console.info('Http server started');
  console.info(`Environment selected: ${nodeEnv}`);
  console.info(`Listening on port: ${expressPort}`);
});

module.exports = app;
```

I'm not receiving any type of error. I am receiving a 302 response from my auth endpoint and it is hitting my callback endpoint. It just never has an access token or user info. When looking at `appSession`, it's always empty. I've tried stepping through some of the code but not sure exactly where the `appSession` should be getting populated.

**Comment by dasarindam** [comment] 2021-05-17 11:21
I am also having similar issue. I tried to add almost all the console log. I am Assuming this MW support all kind of Open-Id connect.
For my case it direct to login page -> land back to callback page. I see the form_data inside the Chrome developer console but cant see the same data or token in the oidc. 
The same openid token call works fine in Postman,

**Comment by adamjmcgrath** [comment] 2021-05-17 12:39
@askurat - I've tried running the `app.js` you've shared and I'm able to login successfully.

The only thing I noticed was that visiting `/` when not logged in threw an error because `req.oidc.user` is undefined.

Couple of things to try:
- `DEBUG=express-openid-connect* node app.js` will print a bit more debugging information
- Try an older version of `express-openid-connect` to rule out a recent change (`2.2` or `2.3`?)
- Step through the callback handler starting [here](https://github.com/auth0/express-openid-connect/blob/master/middleware/auth.js#L71), `appSession` is set [here](https://github.com/auth0/express-openid-connect/blob/master/middleware/auth.js#L132), add a break point [here](https://github.com/auth0/express-openid-connect/blob/master/middleware/auth.js#L138) to see if an error is being swallowed somewhere
- confirm what version of Node you are using
- Check auth0 or your identity providers logs for any errors

**Comment by askurat** [comment] 2021-05-17 15:58
@adamjmcgrath - I ran in debug mode and here is what I got when hitting my login route:
```
 express-openid-connect:client the issuer does not support RP-Initiated Logout +0ms
  express-openid-connect:context req.oidc.login() called with returnTo: http://localhost:5000/login +0ms     
  express-openid-connect:getLoginState adding default state { returnTo: 'http://localhost:5000/login' } +0ms 
  express-openid-connect:context response_type includes code, the authorization request will use PKCE +1ms   
  express-openid-connect:context redirecting to https://testloginroute.com (I redacted my auth url here) +3ms
  express-openid-connect:appSession session was deleted or is empty, clearing all matching session cookies +0ms
  express-openid-connect:appSession session was deleted or is empty, clearing all matching session cookies +118ms
```

- I tried going back to version 2.2.1 but still get the same info.
- I tried setting the breakpoints in the callback handler but none of them ever get hit. I even tried setting a console log at each breakpoint but it also never gets hit.
- Node version is v14.17.0

**Comment by adamjmcgrath** [comment] 2021-05-17 17:01
> I tried setting the breakpoints in the callback handler but none of them ever get hit.

What is the url in the address bar when you get returned back to your site after login? Do you see anything in the browser?

**Comment by askurat** [comment] 2021-05-17 17:06
`http://localhost:5000/login/cb?code=[REDACTED]&state=[REDACTED]&scope=profile+email`

The browser hits my callback url and displays `Hello undefined` because `req.oidc.user` is undefined.

**Comment by adamjmcgrath** [comment] 2021-05-17 17:19
According to your config:

```js
routes: {
  callback: '/cb',
},
```

And assuming your `process.env.BASE_URL` is `http://localhost:5000/`

Then your `redirect_uri` in your `/authorize` request should be `http://localhost:5000/cb`, but it looks like your being redirected directly to `http://localhost:5000/login/cb` by your IDP after login.

>   express-openid-connect:context redirecting to https://testloginroute.com (I redacted my auth url here) +3ms

Can you share the full auth url, there's nothing secret in there, or at least the `redirect_uri` parameter?

**Comment by askurat** [comment] 2021-05-17 19:00
My base url is `http://localhost:5000/login`. My redirect_uri is `http://localhost:5000/login/cb`. My callback endpoint does get hit,

```
app.get('/login/cb', (req, res) => {
  res.send(`hello ${req.oidc.user}`);
});

```

**Comment by adamjmcgrath** [comment] 2021-05-17 20:17
Ah, ok. I see what's happening.

The auth middleware creates a callback handler at `/login/cb`, this will process the `code` and `state` parameters and establish a session.

It can't do this however as you are overriding the callback handler by creating a route at the same url: `app.get('/login/cb', (req, res) => { ... })`

If you remove this route, the callback handler created by the auth middleware will handle the auth callback and log you in.

**Comment by dasarindam** [comment] 2021-05-18 12:36
Remove the method. Keep the routers URL. If you are using redirect_url then keep the router and redirect_url same. 

app.get('/login/cb', (req, res) => {
  res.send(`hello ${req.oidc.user}`);
});

I tested today as per above suggestion. Works fine.

**Comment by askurat** [comment] 2021-05-18 15:37
@adamjmcgrath Ah, got it. This does seem to work if my base url is: `http://localhost:5000`, however it doesn't work if I want my base url to be `http://localhost:5000/login` and my callback to be `/cb`. It hits my login endpoint just fine but I get a `Not Found` error on the callback. I think it is trying to create the route at `/cb` instead of `/login/cb`. I assumed it would create it off of the base url.

If I change my callback to `/login/cb`, I get an error from my provider: `Invalid redirect_uri http://localhost:5000/login/login/cb`.

**Comment by adamjmcgrath** [comment] 2021-05-18 16:04
Hi @askurat - if the base url of your application is `http://localhost:5000` then you should set `BASE_URL` to `http://localhost:5000`.

That `BASE_URL` value should accurately reflect the base url of your express application.

**Comment by dasarindam** [comment] 2021-05-18 16:41
> 
> 
> @adamjmcgrath Ah, got it. This does seem to work if my base url is: `http://localhost:5000`, however it doesn't work if I want my base url to be `http://localhost:5000/login` and my callback to be `/cb`. It hits my login endpoint just fine but I get a `Not Found` error on the callback. I think it is trying to create the route at `/cb` instead of `/login/cb`. I assumed it would create it off of the base url.
> 
> If I change my callback to `/login/cb`, I get an error from my provider: `Invalid redirect_uri http://localhost:5000/login/login/cb`.

Can u Remove the redirect_url (if u r using), just use one callback ('/login/cb') ?  

use only this . routes: { callback: '/login/cb', }, Once the login success then it will be fall back to same router (/). Then you may redirect. 

in my set up I have  http://localhost:5000/Brok/callBack.

auth url -> /Brok/callPartner (with auth required param) 
call back -> /Brok/callBack
base url -> http://localhost:5000

**Comment by adamjmcgrath** [comment] 2021-05-27 10:22
Hi @dasarindam - I'm sorry, I don't understand your question

@askurat - let me know if you're happy for me to close this issue, or if you have any other questions

**Comment by dasarindam** [comment] 2021-05-31 09:40
> 
> 
> Hi @dasarindam - I'm sorry, I don't understand your question
> 
> @askurat - let me know if you're happy for me to close this issue, or if you have any other questions

@adamjmcgrath I was just to add some info and get some solution from the above thread.
Can you suggest if I can pass a different call back URL during runtime ? Or Can is it possible to pass some parameter during the runtime ?

**Comment by askurat** [comment] 2021-05-31 18:56
@adamjmcgrath Sorry for the delay. Yes you can close this issue. Thanks again for the help.

**Comment by adamjmcgrath** [comment] 2021-06-01 12:18
Thanks @askurat 

@dasarindam - your question is not related to this issue. If you'd like help, raise a new issue explaining what errors you are seeing and the steps to reproduce them and we can assist you

**Closed by adamjmcgrath** 2021-06-01 12:18 UTC
Labels: question
