### ISSUE TITLE
 Getting bad request error on login: BadRequestError: checks.state argument is missing

### ISSUE THREAD

**Issue by appagg** [auth0/express-openid-connect#173] opened 2020-12-28 03:09 UTC
### Describe the problem

Login callback returns Bad Request error after a successful login. Exception from server side:

 BadRequestError: checks.state argument is missing
 at callbackStack (/.../node_modules/express-openid-connect/middleware/auth.js:105:31)

### What was the expected behavior?

Successful login callback and redirect to the set URL.

### Reproduction
1. using Firefox browser 84.0.1 (64-bit)
2. login to Auth0 using email account (not social account like google)
3. open another private browser window (or another tab in the same window)
4. login to the same email account
5. at the end of the login, the callback returns Bad Request error

auth0Config:
`        "auth0Config": {
            "authRequired": false,
            "auth0Logout": true,
            "secret": "...",
            "baseURL": "https://www.joyridesclub.com",
            "routes": {"postLogoutRedirect": "https://www.joyridesclub.com/loggedout"},
            "clientID": "...",
            "issuerBaseURL": "..."
        }`

### Environment

Node/Express web server
"express-openid-connect": "^2.1.0",

**Comment by adamjmcgrath** [comment] 2020-12-30 10:45
Hi @appagg - thanks for raising this

I'm not able to reproduce the issue using the steps you provided on FF 84.0.1, either locally or on https://www.joyridesclub.com

Do you have the default privacy settings for FF? Are there any other steps you can provide to help me reproduce the issue?

**Comment by appagg** [comment] 2020-12-30 22:07
Thanks for checking, I tried the same steps in Chrome and it worked fine too. Wondering what's affecting my FF. When I opened the second tab after the login, it's not treating it as logged in. The site uses a rest call to check if it's login and in the server side it uses "req.oidc.isAuthenticated()" to check. 

I've attaced a video to show the FF issue.

https://user-images.githubusercontent.com/1781887/103383623-3e975b80-4aa8-11eb-925d-00143257e136.MP4

**Comment by appagg** [comment] 2021-01-03 20:33
After the login, there's a 'appsession' in the first tab. For the sencond tab, the 'appsession" is missing in the cookies. Looks like the auth middleware wasn't able to send back the session for some reason.

**Comment by adamjmcgrath** [comment] 2021-01-06 11:43
Hi @appagg - I'm not able to see you video (it plays blank for me)

> After the login, there's a 'appsession' in the first tab. For the sencond tab, the 'appsession" is missing in the cookies. 

I'm not sure why 2 tabs on the same domain would have different cookies, are the urls the same?

**Comment by adamjmcgrath** [comment] 2021-01-18 11:32
Hi @appagg - closing this issue, happy to reopen it if you want any further assistance

**Closed by adamjmcgrath** 2021-01-18 11:32 UTC
Labels: question
