### ISSUE TITLE
TypeError: "session.transient" is not allowed

### ISSUE THREAD

**Issue by fire015** [auth0/express-openid-connect#156] opened 2020-10-30 12:02 UTC
According to the `SessionConfigParams` you should be able to set the transient property like so:

```
app.use(
  auth({
    session: {
      transient: true,
    },
  })
);
```

However this throws `TypeError: "session.transient" is not allowed`.

The correct code is:

```
app.use(
  auth({
    session: {
      cookie: {
        transient: true,
      },
    },
  })
);
```

But this is not how it is defined in the interface.

Using version 2.0.0.

**Comment by adamjmcgrath** [comment] 2020-10-30 13:11
Thanks for raising this @fire015 

Going to close this as it's a duplicate of #149

**Closed by adamjmcgrath** 2020-10-30 13:11 UTC
