### ISSUE TITLE
in-flight request re-establishes `appSession` cookie that is cleared by `/logout`

### ISSUE THREAD

**Issue by samm81** [auth0/express-openid-connect#446] opened 2023-03-06 20:21 UTC
### Describe the problem

I have a logout button which does two things:
1. `window.location.assign('/logout')`
2. sends a `fetch` to the server with logging information (the user pressed the logout button)

the `/logout` redirect finishes successfully and clears the cookies (as best I can tell), but the problem is that the `fetch` comes back from the server after `/logout` clears the cookies, and it still has the `appSession` cookie, which it then sets, effectively immediately logging the user back in. 

![image](https://user-images.githubusercontent.com/1221372/223221332-82e7f5bc-525a-4fb7-95de-16d767c4ce94.png)

^ the selected `update` request has the `appSession` cookie, and it's coming back to the browser after the `/logout` request which clears the `appSession` cookie

### What was the expected behavior?

does the cookie need to be set on every request? I don't think I would expect the response from my update request to set the `appSession` cookie. or maybe when `authRequired` is false, the `appSession` cookie would only get sent in routes that `requiresAuth()` ?

or maybe I'm missing something else here ?

### Reproduction

I'll look into minimizing my app if it's useful!

### Environment

- `express-openid-connect` `2.12.0`
- `expressjs`
- firefox 109.0.1

**Comment by samm81** [comment] 2023-03-06 20:25
as a workaround, I've simply moved all my routes that don't require auth to before the `app.use(auth(authConfig))` call

**Comment by adamjmcgrath** [comment] 2023-03-07 10:28
Hi @samm81 - thanks for raising this

This is expected behaviour and the result of having a stateless session - if you logout and clear the user agent's cookies, but a concurrent request shows up later with a valid cookie then it will authenticate the request, it has no state to tell it otherwise.

This is also exacerbated by the fact that, since the session is a rolling session, the cookie expiry get's updated on every request. So a concurrent request will write a new cookie after the logout request has deleted it.

If your workaround resolves the issue for you great, your other options are to manage the concurrency of these authenticated requests in your application or use a stateful session with a custom session store (see [example](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#9-use-a-custom-session-store))

**Comment by samm81** [comment] 2023-03-09 22:46
thanks for the quick reply @adamjmcgrath , the stateless part makes sense, I guess what I was confused about is why *all* responses set the login cookie, which makes now makes sense given the explanation of the rolling session.

I suppose there's no way to mark routes with some sort of "don't update rolling session" ?

**Comment by adamjmcgrath** [comment] 2023-03-10 08:16
Hi @samm81 - there's no way to do this at the moment. But I've added this to the list of possible new features for the next time we work on a major. 

Closing as I think https://github.com/auth0/express-openid-connect/issues/446#issuecomment-1457926018 has answered your question

**Closed by adamjmcgrath** 2023-03-10 08:16 UTC
