### ISSUE TITLE
Multi tenant usage of auth()

### ISSUE THREAD

**Issue by cpereyra5199** [auth0/express-openid-connect#381] opened 2022-08-06 07:39 UTC
### Describe the problem you'd like to have solved

When redirecting to my server using the address bar, the auth flow functions as expected.  However, when using a link that points the same server url I type into the address bar, the auth flow returns an error

`BadRequestError: checks.state argument is missing
    at /Users/carlospereyra/esm-api/node_modules/express-openid-connect/middleware/auth.js:121:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

### Describe the ideal solution

Auth flow should behave the same whether flow is triggered from a link or directly from a server.

**Comment by adamjmcgrath** [comment] 2022-08-22 08:48
Hi @cpereyra5199 - thanks for raising this

> When redirecting to my server using the address bar, the auth flow functions as expected. However, when using a link that points the same server url I type into the address bar, the auth flow returns an error

tbh, I'm not sure what this means or what it has to do with multi tenant usage

Could you try detailing the steps you are using to reproduce the issue, what outcomes you actually get and what outcomes you expect.

Also sharing some code or, preferably, an example repro that demonstrates the issue would be helpful.

**Comment by adamjmcgrath** [comment] 2022-09-07 08:10
Closing due to innactivity

**Closed by adamjmcgrath** 2022-09-07 08:10 UTC
Labels: question
