### ISSUE TITLE
Not Able to use with providers returning jwt id_token

### ISSUE THREAD

**Issue by mnadeem** [auth0/express-openid-connect#388] opened 2022-09-25 15:07 UTC
### Describe the problem

If an IDP returns jwt in id_token instead of in access token, I am getting the following error

```
Invalid client: Possible causes may be missing / invalid client_id, missing client authentication, invalid or expired client secret, invalid or expired 
JWT authentication, or a mismatch between registered and submitted client authentication method
```

### What was the expected behavior?

It should work if jwt is returned in id_token

### Reproduction

Use an IDP which returns jwt in id_token.

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:** ^2.8.0
- **Which framework are you using, if applicable:** express
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by mnadeem** [comment] 2022-09-27 06:38
```
auth({
    authRequired: false,
    baseURL: APP_BASE_URL,
    issuerBaseURL: OIDC_OHID_ISSUER_BASE_URL,
    clientID: OIDC_OHID_CLIENT_ID,
    clientSecret: OIDC_OHID_CLIENT_SECRET,
    secret: OIDC_ENCRYPTION_KEY_SECRET,
    idpLogout: true,
    idTokenSigningAlg: 'HS256',
    authorizationParams: {
        response_type: 'code',
        scope: 'openid profile email phone address',
    },
    session: {
        rollingDuration: OIDC_SESSION_MAX_IDLE_TIME_IN_SEC,
        cookie: { path: '/' }
    },
})
```

Still getting the same error, I feel like only accesstoken is parsed (In my cased access token is not JWT) in express-openid-connect and id_token is not parsed.

**Comment by adamjmcgrath** [comment] 2022-09-28 09:09
I'm not able to reproduce your issue with `HS256` signed ID Token JWTs and opaque Access Tokens.

Could you share the header of your ID Token and your Issuer Base Url?

**Comment by mnadeem** [comment] 2022-09-29 13:41
<img width="300" alt="image" src="https://user-images.githubusercontent.com/476145/193046834-94cd5ea0-1f9c-496b-88a6-9277523c9c1f.png">

header
```
{
  "kid": "855f5769-9d20-440f-a157-0ff3f6dcdcd3",
  "alg": "ES256"
}
```

```
OIDC_OHID_ISSUER_BASE_URL=https://id.np.onehealthcareid.com
```

You can can reproduce your issue, if you use an IDP which returns JWT in id token, and access token should not be JWT

**Comment by mnadeem** [comment] 2022-09-29 14:14
Full error

```
{"level":"error","time":1664460806987,"pid":54176,"msg":"OIDC Error occurred: {\"message\":\"invalid_client (Invalid client: Possible causes may be missing / invalid client_id, missing client authentication, invalid or expired client secret, invalid or expired JWT authentication, or a mismatch between registered and submitted client authentication method)\",\"error\":\"invalid_client\",\"error_description\":\"Invalid client: Possible causes may be missing / invalid client_id, missing client authentication, invalid or expired client secret, invalid or expired JWT authentication, or a mismatch between registered and submitted client authentication method\"}"}
```

**Comment by adamjmcgrath** [comment] 2022-09-29 16:37
>   "alg": "ES256"

If your ID Token is signed with `ES256` then you should set `idTokenSigningAlg` to `ES256`

**Comment by mnadeem** [comment] 2022-09-30 07:10
Yeah tried that as well, no luck

**Comment by adamjmcgrath** [comment] 2022-09-30 10:56
ok, so per the error message this is a configuration issue, either:

> missing / invalid client_id

Check your Client ID is correct

> missing client authentication, invalid or expired client secret

Check your Client Secret is correct

> invalid or expired JWT authentication, or a 

(You're not using JWT authentication)

> mismatch between registered and submitted client authentication method

What is your registered client authentication method? The default for this SDK is `client_secret_basic`

> https://id.np.onehealthcareid.com

I can't access your IDPs `/.well-known/openid-configuration` - so I can't tell you how your client should be configured

**Comment by mnadeem** [comment] 2022-09-30 12:19
Here are some of the items of /.well-known/openid-configuration



```
  "code_challenge_methods_supported" : [ "S256" ],
  "response_modes_supported" : [ "query" ],
  "subject_types_supported" : [ "public" ],
  "id_token_signing_alg_values_supported" : [ "HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512" ],
  "response_types_supported" : [ "code" ],
  "grant_types_supported" : [ "authorization_code", "refresh_token", "client_credentials" ],
  "token_endpoint_auth_methods_supported" : [ "none", "client_secret_basic", "client_secret_post" ],
  "claim_types_supported" : [ "normal" ],
  "claims_parameter_supported" : false,
  "request_parameter_supported" : false,
  "request_uri_parameter_supported" : false,
  "frontchannel_logout_supported" : false,
```

**Comment by mnadeem** [comment] 2022-09-30 12:21
Validated all the details by logging in the console, no luck

**Comment by mnadeem** [comment] 2022-09-30 14:31
This is what I am bringing up, express-openid-connect is looking for jwt in access_token, and failing, it should look for jwt in id_token as well

```
invalid or expired JWT authentication, or a
```

**Comment by adamjmcgrath** [comment] 2022-10-03 12:34
> express-openid-connect is looking for jwt in access_token, and failing, it should look for jwt in id_token as well

All OIDC ID tokens are JWTs, express-openid-connect as an OIDC client expects the ID Token as a JWT. In addition to this express-openid-connect, as an OIDC client, doesn't care what format the access token is in - the access token is completely opaque to the client (this SDK).

The only thing I can suggest is that you provide a reproducible example and I can debug it for you.

**Comment by mnadeem** [comment] 2022-10-04 08:39
Here is an example

https://github.com/mnadeem/oidc-express-multi-providers

.env

```
PORT=3005
REACT_APP_IS_SSO_DISABLED=true
#HTTPS=true
#NODE_TLS_REJECT_UNAUTHORIZED=0
#SKIP_PREFLIGHT_CHECK=true

# APP
APP_ENV=dev
APP_BASE_URL=https://localhost
APP_AUTHORIZED_ROLES=lob_app_Admin


OIDC_ENCRYPTION_KEY_SECRET=asdfgaswtdgw5tq34gq33tg56354ygh897ke57u6W3R124FWER
OIDC_SESSION_MAX_IDLE_TIME=1800

# SSO : https://auth0.github.io/express-openid-connect/interfaces/configparams.html
OIDC_PF_ISSUER_BASE_URL=https://pf.lob.com
OIDC_PF_CLIENT_ID=clientID
OIDC_PF_CLIENT_SECRET=afsdasdfsd3r3rdsafsdf


OIDC_OHID_ISSUER_BASE_URL=https://ohid.com
OIDC_OHID_CLIENT_ID=clientID
OIDC_OHID_CLIENT_SECRET=asfsadfsdfasf
```

```
npm install
npm run dev:server
```

**Comment by adamjmcgrath** [comment] 2022-10-05 11:51
@mnadeem - thanks for sharing the example

I'm able to successfully login to that app with a correctly configured Identity Provider (see https://github.com/mnadeem/oidc-express-multi-providers/compare/main...adamjmcgrath:oidc-express-multi-providers:main#diff-653c1004be852b5a23ac0a0060bde2f9cfe37d04f13334cfcc64be046c62237c)

- checkout https://github.com/adamjmcgrath/oidc-express-multi-providers
- npm install
- npm run dev:server
- visit http://localhost:3000
- login with any credentials
- get the following:

![image](https://user-images.githubusercontent.com/1299658/194053545-6845a086-6e7f-484d-874a-d5ce4bf0b13a.png)

**Comment by adamjmcgrath** [comment] 2022-10-13 15:21
Closing, as I believe this is working as expected - @mnadeem, feel free to ping me if you can provide a failing example

**Closed by adamjmcgrath** 2022-10-13 15:21 UTC
Labels: question
